# Generated by Django 3.2.13 on 2022-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slider_image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='category',
            name='slider_image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='category',
            name='slider_image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
